apiVersion: v1
kind: Service
metadata:
  name: sf2-web-svc
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 31080
    - name: "https-port"
      protocol: "TCP"
      port: 8443
      targetPort: 443
      nodePort: 31443
  selector:
    app: sf2-web
